### ISSUE TITLE
Error setting up entry Alpha Innotec MSW 10 260321-0257 for luxtronik2 on HA2023.5.0

### ISSUE THREAD

**Issue by gdiciancia** [BenPru/luxtronik#100]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/luxtronik/__init__.py:62
Integration: luxtronik
First occurred: 8:41:54 AM (1 occurrences)
Last logged: 8:41:54 AM

Error setting up entry Alpha Innotec MSW 10 260321-0257 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/luxtronik/__init__.py", line 62, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by gdiciancia** [comment]
False alarm. Issue can be deleted.
