### ISSUE TITLE
Test Version Migration from 2023.03.24

### ISSUE THREAD

**Issue by BenPru** [BenPru/luxtronik#164]
- [ ] Are all entities migrated succesfull from 2023.03.24 to 2023.10.*?
- [ ] Check discover heatpump function
- [ ] Document the breaking changes
- [x] Missing sensor: switchoff_reason

* New sensors
  * pump_flow_delta_target calc 239
  * pump_flow_delta calc 240
  * circulation_pump_delta_target calc 242
  * circulation_pump_delta calc 243
* New numbers
  * release_time_second_heat_generator param 992 ID_Einst_Freigabe_Zeit_ZWE

| Legacy Name | New Name | Luxtronik Key | Comment |
|--------|--------|--------|--------|
| **climate**.domestic_water | **water_heater**.domestic_water | | Losing historical data!!! | 
| number.* | | |
| **domestic_water**_target_temperature | **dhw**_target_temperature | 0002 parameters.ID_Einst_BWS_akt| | 
| **domestic_water**_hysteresis | **dhw**_hysteresis | 0074 parameters.ID_Einst_BWS_Hyst_akt| | 
| **domestic_water**_thermal_desinfection_target | **dhw**_thermal_desinfection_target | 0047 parameters.ID_Einst_LGST_akt| | 
| cooling_target_temperature | cooling_target_temperature_mk1 / cooling_target_temperature_mk2 / cooling_target_temperature_mk3 | | |
| sensor.* | | |
| **domestic_water**_temperature | **dhw**_temperature | 0017 calculations.ID_WEB_Temperatur_TBW | |
| operation_hours_domestic_water | dhw_operation_hours | 0065 calculations.ID_WEB_Zaehler_BetrZeitBW | |
| heat_amount_domestic_water | dhw_heat_amount | 0152 calculations.ID_WEB_WMZ_Brauchwasser | |
| **domestic_water**_energy_input | **dhw**_energy_input | 1137 parameters.Unknown_Parameter_1137 | |
| compressor_impulses | compressor**1**_impulses | 0057 calculations.ID_WEB_Zaehler_BetrZeitImpVD1| unit_of_measurement: Anzahl -> ∑ | 
| compressor**_impulses2** | compressor**2_impulses** | 0059 calculations.ID_WEB_Zaehler_BetrZeitImpVD2 | |
| **operation_hours_compressor1** | **compressor1_operation_hours** |0056 calculations.ID_WEB_Zaehler_BetrZeitVD1| | 
| **operation_hours_compressor2** | **compressor2_operation_hours** |0058 calculations.ID_WEB_Zaehler_BetrZeitVD2| |
| operation_hours_additional_heat_generator | additional_heat_generator_operation_hours | 0060 calculations.ID_WEB_Zaehler_BetrZeitZWE1 | |
| room_temperature | room_thermostat_**temperature** | 0227 calculations.ID_WEB_RBE_RT_Ist | |
| room_**target_temperature** | room_**thermostat_temperature_target** | 0228 calculations.ID_WEB_RBE_RT_Soll | |
| binary_sensor.* | | | 
| **domestic_water**_recirculation_pump | **dhw**_recirculation_pump |0038 calculations.ID_WEB_BUPout| | 
| **domestic_water**_circulation_pump | **dhw**_circulation_pump |0046 calculations.ID_WEB_ZIPout| | 
| **domestic_water**_charging_pump | **dhw**_charging_pump |0046 calculations.ID_WEB_ZIPout| |

**Comment by Kars-de-Jong** [comment]
@BenPru I tested a migration from version 2023.9.10 to 2023.10.16-Beta on my Home Assistant test instance, which has no access to the heatpump. It failed, with the following relevant log entries:

```
2023-10-25 12:49:23.865 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry Alpha Innotec MSW2-6S 311111-0729 for luxtronik2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 658, in async_migrate
result = await component.async_migrate_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/luxtronik2/__init__.py", line 87, in async_migrate_entry
await _async_delete_legacy_devices(hass, config_entry)
File "/config/custom_components/luxtronik2/__init__.py", line 274, in _async_delete_legacy_devices
coordinator = LuxtronikCoordinator.connect(hass, config_entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/luxtronik2/coordinator.py", line 206, in connect
client = Luxtronik(
^^^^^^^^^^
File "/config/custom_components/luxtronik2/lux_helper.py", line 188, in __init__
self.read()
File "/config/custom_components/luxtronik2/lux_helper.py", line 202, in read
self._read_write(write=False)
File "/config/custom_components/luxtronik2/lux_helper.py", line 218, in _read_write
self._socket.connect((self._host, self._port))
TimeoutError: [Errno 110] Operation timed out
```

After that, another error was logged:
```
2023-10-25 12:49:23.870 ERROR (MainThread) [custom_components.luxtronik2] Unexpected exception when checking if a socket is closed
Traceback (most recent call last):
File "/config/custom_components/luxtronik2/lux_helper.py", line 150, in _is_socket_closed
data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 107] Socket not connected
```

It also seems to do things that take a long time on the main thread, because Home Assistant complains further:
```
2023-10-25 12:49:24.051 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2023-10-25 12:49:24.051 WARNING (MainThread) [homeassistant.setup] Setup of input_button is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of schedule is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of tag is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2023-10-25 12:49:24.052 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rest is taking over 10 seconds.
2023-10-25 12:49:24.136 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform rest is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2023-10-25 12:49:45.890 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-10-25 12:49:45.890 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-10-25 12:54:55.965 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward
2023-10-25 12:55:10.968 WARNING (MainThread) [homeassistant.core] Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: <list of all integrations suppressed>
```

**Comment by BenPru** [comment]
> which has no access to the heatpump. It failed

Yes, the migration need a connection to the heatpump to detect the devices. Without connection the migration can not run successfull.

**Comment by AJediIAm** [comment]
All done
