### ISSUE TITLE
Error in 2023.10.31-beta

### ISSUE THREAD

**Issue by ChrisMisker** [BenPru/luxtronik#183]
Thank you so much for the hard work on this!
The integration can’t be set up due to this error:
```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 06:26:33 (1 occurrences)
Last logged: 06:26:33

Setup failed for custom integration luxtronik2: Unable to import component: Exception importing custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 13, in <module>
    from .const import (
  File "/config/custom_components/luxtronik2/const.py", line 62, in <module>
    SERVICE_WRITE_SCHEMA = vol.Schema(
                           ^^^
NameError: name 'vol' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2
```

**Comment by scaronni** [comment]
Same issue. Thanks.

**Comment by qubabos** [comment]
Same here : {"message":"Invalid handler specified"} during initial config.

**Comment by ChrisMisker** [comment]
The 11.1 beta fixed this, thanks.
