### ISSUE TITLE
Could not handle config_flow.async_step_options

### ISSUE THREAD

**Issue by Laemmchen1780** [BenPru/luxtronik#192]
Hi @BenPru ; many thanks for your work and best regards from Uedem to Kleve. 

I got this error message by initial setup in the integrations section: 

_Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/config_flow.py:224
Integration: Luxtronik
First occurred: 14:37:09 (12 occurrences)
Last logged: 14:50:36

Could not handle config_flow.async_step_options {'host': '192.168.8.41', 'port': 8889, 'timeout': 60, 'max_data_length': 10000}
Could not handle config_flow.async_step_options {'host': '192.168.8.41', 'port': 8889, 'timeout': 61, 'max_data_length': 9999}
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/config_flow.py", line 224, in async_step_options
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1597, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured_

Can someone explain whats wrong here?

**Comment by Laemmchen1780** [comment]
Found it already, there was a disabled Luxtronic Integration i was not aware of. Thanks.
