### ISSUE TITLE
Invalid handler specified

### ISSUE THREAD

**Issue by TechSaiyajin** [BenPru/luxtronik#260]
Hallo,

mit 3abc4df bekomme ich nun folgende Fehlermeldung wenn ich die Integration hinzufügen möchte:

"Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}"

Schon probiert:
Neustart und Integration erneut aus dem HACS geladen.

WP Firmware: V2.88.3
Core: 2024.7.1
Supervisor: 2024.06.2
Operating System: 12.4

**Comment by AJediIAm** [comment]
Same issue.

I copied the code manually to test and got the following error:

'''
Logger: homeassistant.loader
Source: loader.py:1050
First occurred: 19:56:33 (2 occurrences)
Last logged: 19:56:33

Unexpected exception importing component custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1050, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 40, in <module>
    from .lux_helper import Luxtronik, get_manufacturer_by_model
  File "/config/custom_components/luxtronik2/lux_helper.py", line 280
    await asyncio.sleep(WAIT_TIME_WRITE_PARAMETER)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside async function
'''

**Comment by BenPru** [comment]
As short-term workaround a have removed the sleep.
So it should work at the moment. But the written value is not visible immediately. It is update in the next update interval after 60 seconds.
