### ISSUE TITLE
New integration setup fails with 2024.9.29-Beta

### ISSUE THREAD

**Issue by Jeanlucpica** [BenPru/luxtronik#270]
First, let me take the chance to thank you for this great integration and the continuous support 👍!

I believe with 2024.9.29-Beta the setup of luxtronik as a new integration is broken. When adding the heatpump with the correct data, the integration setup does not complete and no devices/entities are created. Here is the corresponding logfile entry. I am running a standard HassOS installation.

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 12:20:34 (6 occurrences)
Last logged: 12:23:19

Error setting up entry Novelan LD7 280508-0137 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/switch.py", line 18, in <module>
    from .switch_entities_predefined import SWITCHES
  File "/config/custom_components/luxtronik2/switch_entities_predefined.py", line 48, in <module>
    update_interval=UPDATE_INTERVAL_VERY_SLOW,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'UPDATE_INTERVAL_VERY_SLOW' is not defined. Did you mean: 'UPDATE_INTERVAL_NORMAL'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 48, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2108, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 4 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1284, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.luxtronik2.switch
```

I could solve the issue by downgrading to 2024.9.23-Beta and performing the setup of the luxtronik integration without issues. The update to 2024.9.29-Beta was no problem afterwards and its running fine now. I hope this logfile maybe helps to find the issue in the last releases.

**Comment by BenPru** [comment]
Please delete the integration with hacs and reinstall 2024.9.29-Beta. This is fixed with the latest beta.
