### ISSUE TITLE
Error/Warning using latest version 2024.9.30

### ISSUE THREAD

**Issue by blue-bean** [BenPru/luxtronik#278]
Using the latest 2024.9.30 i found in the protocol 

2024-10-04 09:05:17.785 ERROR (MainThread) [custom_components.luxtronik2] Could not handle config_flow.async_step_dhcp DhcpServiceInfo(ip='192.168.192.11', hostname='heizung', macaddress='05d15ed0e50b')
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/config_flow.py", line 269, in async_step_dhcp
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2395, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

2024-10-04 09:05:18.260 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wp_heizung_tagesverbrauch (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-10-04 09:05:18.261 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wp_heizung_tageserzeugnis (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-10-04 09:05:18.261 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.wp_warmwasser_tageserzeugnis (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

2024-10-04 09:05:18.340 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 108, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1296, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1331, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 527, in _async_handle_step
    if result.get("preview") is not None:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by BenPru** [comment]
@blue-bean Which HA Verson do you use?

**Comment by blue-bean** [comment]
Core 2024.9.3
Supervisor 2024.09.1
Operating System 12.4
Frontend 20240909.1

**Comment by blue-bean** [comment]
Same error with core 2024.10.0

**Comment by BenPru** [comment]
Duplicate #216
