### ISSUE TITLE
Error migrating entry

### ISSUE THREAD

**Issue by henne49** [BenPru/luxtronik#284]
Hi, 

I used the bouni luxtronik integration first and then switched to yours now. when I'm trying to migrate from below version, the migration fails and I have no idea how to fix. If I remove the integration and re-add , it works. But then all Dashboards and automations are broken. 

Thank you very much for your work here, really appreciated!

Installed Version 2023.9.10
New Version 2024.9.30

below is the error:
Error migrating entry "removed" for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 112, in async_migrate_entry
    config_entry.version = 3
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead

2024-10-13 14:59:21.448 INFO (MainThread) [homeassistant.setup] Setting up luxtronik2
2024-10-13 14:59:21.449 INFO (MainThread) [homeassistant.setup] Setup of domain luxtronik2 took 0.00 seconds
2024-10-13 14:59:21.449 DEBUG (MainThread) [custom_components.luxtronik2] Migrating from version 2
2024-10-13 14:59:21.451 INFO (MainThread) [custom_components.luxtronik2] Connected to Luxtronik heatpump X.X.X.X:8889 with timeout 60.0s
2024-10-13 14:59:21.455 DEBUG (MainThread) [custom_components.luxtronik2] Command 3003
2024-10-13 14:59:21.456 DEBUG (MainThread) [custom_components.luxtronik2] Length 1141
2024-10-13 14:59:21.459 DEBUG (MainThread) [custom_components.luxtronik2] Read 1141 parameters
2024-10-13 14:59:21.461 DEBUG (MainThread) [custom_components.luxtronik2] Command 3004
2024-10-13 14:59:21.504 DEBUG (MainThread) [custom_components.luxtronik2] Stat 0
2024-10-13 14:59:21.504 DEBUG (MainThread) [custom_components.luxtronik2] Length 263
2024-10-13 14:59:21.505 DEBUG (MainThread) [custom_components.luxtronik2] Read 263 calculations
2024-10-13 14:59:21.507 DEBUG (MainThread) [custom_components.luxtronik2] Command 3005
2024-10-13 14:59:21.556 DEBUG (MainThread) [custom_components.luxtronik2] Length 365
2024-10-13 14:59:21.557 DEBUG (MainThread) [custom_components.luxtronik2] Read 365 visibilities
2024-10-13 14:59:21.559 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry "removed" for luxtronik2
File "/config/custom_components/luxtronik2/__init__.py", line 112, in async_migrate_entry

**Comment by BenPru** [comment]
@BenPru TODO: Change "config_entry.version = 3" to "async_update_entry"

**Comment by AJediIAm** [comment]
@BenPru : is this still relevant?
