### ISSUE TITLE
HA 2022.11.3 and latest version of this plugin panics

### ISSUE THREAD

**Issue by SchumacherFM** [BenPru/luxtronik#29]
hey, I just pulled in via `git pull --rebase -p` your latest version 9afb32724a5a2cac7c14af870da1189bec9f45f7 and pulled the latest HA version with docker image ID `0b0db9f8d3bc`  Home Assistant 2022.11.3 Frontend 20221108.0 - latest

This error shows up und disables the Luxtronik plugin in HA. Unfortunately I don't speak python:

```
2022-11-20 16:54:38.427 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up luxtronik2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/sensor.py", line 139, in async_setup_entry
    text_time = get_sensor_text(lang, "time")
  File "/config/custom_components/luxtronik2/helpers/helper.py", line 37, in get_sensor_text
    if lang != LANG_DEFAULT and key in __content_locale__:
TypeError: argument of type 'NoneType' is not iterable
2022-11-20 16:54:38.573 ERROR (MainThread) [homeassistant.components.climate] Error while setting up luxtronik2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/climate.py", line 95, in async_setup_entry
    text_heating = get_sensor_text(lang, 'heating')
  File "/config/custom_components/luxtronik2/helpers/helper.py", line 37, in get_sensor_text
    if lang != LANG_DEFAULT and key in __content_locale__:
TypeError: argument of type 'NoneType' is not iterable
2022-11-20 16:54:38.580 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up luxtronik2 platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/binary_sensor.py", line 150, in async_setup_entry
    text_evu_unlocked = get_sensor_text(lang, "evu_unlocked")
  File "/config/custom_components/luxtronik2/helpers/helper.py", line 37, in get_sensor_text
    if lang != LANG_DEFAULT and key in __content_locale__:
TypeError: argument of type 'NoneType' is not iterable
2022-11-20 16:54:38.586 ERROR (MainThread) [homeassistant.components.number] Error while setting up luxtronik2 platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/number.py", line 65, in async_setup_entry
    text_temp = get_sensor_text(lang, 'temperature')
  File "/config/custom_components/luxtronik2/helpers/helper.py", line 37, in get_sensor_text
    if lang != LANG_DEFAULT and key in __content_locale__:
TypeError: argument of type 'NoneType' is not iterable
2022-11-20 16:54:38.971 ERROR (MainThread) [homeassistant.components.switch] Error while setting up luxtronik2 platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/switch.py", line 50, in async_setup_entry
    text_remote_maintenance = get_sensor_text(lang, 'remote_maintenance')
  File "/config/custom_components/luxtronik2/helpers/helper.py", line 37, in get_sensor_text
    if lang != LANG_DEFAULT and key in __content_locale__:
TypeError: argument of type 'NoneType' is not iterable
```

Thanks for having a look.

**Comment by BenPru** [comment]
Thanks for your ticket. It was a problem with the default locale.
Please try [2022.11.20](https://github.com/BenPru/luxtronik/releases/tag/2022.11.20)

**Comment by BenPru** [comment]
Please check the latest version. If the problem persists, please reopen the ticket.
