### ISSUE TITLE
Breaking change: 2025.1.0b2

### ISSUE THREAD

**Issue by AJediIAm** [BenPru/luxtronik#309]
The latest HA beta is unable to load the Luxtronik Version 2024.11.15-Beta.

The following error is reported:
```
Unexpected exception importing platform custom_components.luxtronik2.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 175, in <module>
    class LuxtronikWaterHeaterDescription(
    ...<14 lines>...
        temperature_unit: str = UnitOfTemperature.CELSIUS
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

**Comment by ChrisMisker** [comment]
Same with beta 3!

**Comment by BenPru** [comment]
Please try the current main branch

**Comment by BenPru** [comment]
@ChrisMisker Can you test it again with my last changes in the main branch?

**Comment by ChrisMisker** [comment]
@BenPru Still not working. Not sure if I updated the right way: went to developer tools? Actions, update: install update, entity Luxtronik update, version main. Is that correct?

These errors come up:

```

Logger: homeassistant.loader
Source: loader.py:1075
First occurred: 12:52:40 (2 occurrences)
Last logged: 12:52:41

Unexpected exception importing component custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 182, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 177, in metaclass_resolver
    else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

```

```

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 12:52:41 (1 occurrences)
Last logged: 12:52:41

Setup failed for custom integration 'luxtronik2': Unable to import component: Exception importing custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 182, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 177, in metaclass_resolver
    else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 182, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 177, in metaclass_resolver
    else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2

```

**Comment by BenPru** [comment]
@ChrisMisker Yes, you updated successfully.
Can you try again?

**Comment by ChrisMisker** [comment]
@BenPru still not

```

Logger: homeassistant.loader
Source: loader.py:1075
First occurred: 13:05:59 (2 occurrences)
Last logged: 13:05:59

Unexpected exception importing component custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 181, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 176, in metaclass_resolver
    metaclass = metaclass[0] if len(metaclass)==1 else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
                                                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

```

```

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 13:05:59 (1 occurrences)
Last logged: 13:05:59

Setup failed for custom integration 'luxtronik2': Unable to import component: Exception importing custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 181, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 176, in metaclass_resolver
    metaclass = metaclass[0] if len(metaclass)==1 else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
                                                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 181, in <module>
    metaclass_resolver(LuxtronikEntityDescription, WaterHeaterEntityEntityDescription)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/model.py", line 176, in metaclass_resolver
    metaclass = metaclass[0] if len(metaclass)==1 else type("_".join(mcls.__name__ for mcls in metaclass), metaclass, {})   # class M_C
                                                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'function' is not an acceptable base type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.luxtronik2

```

**Comment by dubakdubak** [comment]
Hi, I can confirm the same problem after updating to HA2025.1.0.
It's really critical for me,as the luxtronik Integration is not functional now :-(
Are there any hopes to make this work soon again?
Many thanks!!!!

**Comment by mgmeulen** [comment]
Hi, indeed also the same issue after updating to HA2025.1 and luxtronic main.  Hope it can be fixed soon. Appreciate your work!

**Comment by AJediIAm** [comment]
> Hi, I can confirm the same problem after updating to HA2025.1.0. It's really critical for me,as the luxtronik Integration is not functional now :-( Are there any hopes to make this work soon again? Many thanks!!!!

Best to restore a backup until it is fixed and

**Comment by AJediIAm** [comment]
Sorry, wrong button...

Best to downgrade(restore backup) until it is fixed.

**Comment by mgmeulen** [comment]
> I found the problem, it is because of [home-assistant/core#132888](https://github.com/home-assistant/core/pull/132888)
> 
> WaterHeaterEntityEntityDescription is now WaterHeaterEntityDescription
> 
> Class WaterHeaterEntityEntityDescription is still available, but deprecated. But apparently this does not work with the function `metaclass_resolver`. My Python skills are limited, but if you change the name in `model.py` to `WaterHeaterEntityDescription`, it works again in my case. But of course this change would break Home Assistant versions <2025.1.

Good find! I can indeed confirm this works! Thanks!

**Comment by ahessling** [comment]
Maybe some with an older version of HA can check if my pull request works.

**Comment by Reepro2580** [comment]
can confirm this fix works on 2025.1

**Comment by ollidiemaus** [comment]
Is there any easy way to checkout main branch with hacs or is this possible only by installing manually ?

**Comment by svasek** [comment]
Hi, 
I've just updated the integration to the commit [9e7f06c](https://github.com/BenPru/luxtronik/commit/9e7f06c4d0881156e254113655082f2ab6d95c6b) and I can confirm it works even on the HA `2024.12.5`.  👍 
Thank you for the fix!

**Comment by ahessling** [comment]
@svasek This was expected because commit 9e7f06c still uses the "old" name `WaterHeaterEntityEntityDescription` which should work until 2024.12.
2025.1 introduces the new name. It would be interesting if my pull request #317 works with the "old" name `WaterHeaterEntityEntityDescription`, .e.g. with HA 2024.12. I know that the PR works in 2025.1, since I tested it myself. But I have no older installation here and I don't want to downgrade.

**Comment by svasek** [comment]
Hi, 
I've just updated the integration to the commit [9e7f06c](https://github.com/BenPru/luxtronik/commit/9e7f06c4d0881156e254113655082f2ab6d95c6b) and and updated file `model.py` to the #317. I can confirm it works even on the HA `2024.12.5`.  👍 
Thank you for the fix!

**Comment by Reepro2580** [comment]
> Is there any easy way to checkout main branch with hacs or is this possible only by installing manually ?

i just replaced the two occurences of WaterHeaterEntityEntityDescription -> WaterHeaterEntityDescription  in model.py. didn't do a real upgrade yet

**Comment by AJediIAm** [comment]
**Manual fix:**
Using the `Studio Code Server` or `File editor` Add-on:
- In `custom_components/luxtronik2/model.py`
  - Update line 23 from `    WaterHeaterEntityEntityDescription,` to `   WaterHeaterEntityDescription,`
  - Update line 177 from `    WaterHeaterEntityEntityDescription,` to `   WaterHeaterEntityDescription,`
- Update to `HA Core 2025.1`
  - Ensure HA is restarted if you already updated.

I didn't need to apply update https://github.com/BenPru/luxtronik/commit/9e7f06c4d0881156e254113655082f2ab6d95c6b myself. Let me know if the steps above didn't work for you so I can extend the instructions to work for everyone.

**Comment by MichaelsSynology** [comment]
Hi @AJediIAm 
the fix worked for me. 
My integration got stuck after updating HA. I just updated this two lines - and it fixed my issue.
Thx :-)

**Comment by andyhomea** [comment]
> **Manual fix:** Using the `Studio Code Server` or `File editor` Add-on:
> 
> * In `custom_components/luxtronik2/model.py`
>   
>   * Update line 23 from `    WaterHeaterEntityEntityDescription,` to `   WaterHeaterEntityDescription,`
>   * Update line 177 from `    WaterHeaterEntityEntityDescription,` to `   WaterHeaterEntityDescription,`
> * Update to `HA Core 2025.1`
>   
>   * Ensure HA is restarted if you already updated.
> 
> I didn't need to apply update [9e7f06c](https://github.com/BenPru/luxtronik/commit/9e7f06c4d0881156e254113655082f2ab6d95c6b) myself. Let me know if the steps above didn't work for you so I can extend the instructions to work for everyone.

Hi, I can confirm this manual fix worked for me. Thanks a lot!

**Comment by dmutsaers** [comment]
@AJediIAm The manual fix worked in my Home Assistant configuration too. No other adjustments have been made.

**Comment by CVB2000** [comment]
> * WaterHeaterEntityDescription

I can also confirm that just changing those two words as you described fixed the problem. Nothing else done, update to 2025.1 works smoothly then.

**Comment by MarcAndreWyss** [comment]
@AJediIAm: Thank you very much. Changing WaterHeaterEntityEntityDescription to WaterHeaterEntityDescription solves the issue.

**Comment by davidcorrio** [comment]
hello
it was working fine after changing `WaterHeaterEntityEntityDescription` to `WaterHeaterEntityDescription` 
i've just updated to 2025.2 and the problem is back:

```
Enregistreur:` homeassistant.loader
Source: loader.py:1075
S'est produit pour la première fois: 15:58:37 (2 occurrences)
Dernier enregistrement: 15:58:37

Unexpected exception importing component custom_components.luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
    from .coordinator import LuxtronikCoordinator
  File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
    from .common import correct_key_value
  File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
    from .model import LuxtronikCoordinatorData
  File "/config/custom_components/luxtronik2/model.py", line 7
    from __future__ import annotations
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by davidcorrio** [comment]
> hello it was working fine after changing `WaterHeaterEntityEntityDescription` to `WaterHeaterEntityDescription` i've just updated to 2025.2 and the problem is back:
> 
> ```
> Enregistreur:` homeassistant.loader
> Source: loader.py:1075
> S'est produit pour la première fois: 15:58:37 (2 occurrences)
> Dernier enregistrement: 15:58:37
> 
> Unexpected exception importing component custom_components.luxtronik2
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
>     ComponentProtocol, importlib.import_module(self.pkg_path)
>                        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/config/custom_components/luxtronik2/__init__.py", line 28, in <module>
>     from .coordinator import LuxtronikCoordinator
>   File "/config/custom_components/luxtronik2/coordinator.py", line 22, in <module>
>     from .common import correct_key_value
>   File "/config/custom_components/luxtronik2/common.py", line 25, in <module>
>     from .model import LuxtronikCoordinatorData
>   File "/config/custom_components/luxtronik2/model.py", line 7
>     from __future__ import annotations
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SyntaxError: from __future__ imports must occur at the beginning of the file
> ```

i reply to myself:
i just copy/past `model.py`  from https://github.com/BenPru/luxtronik/commit/9e7f06c4d0881156e254113655082f2ab6d95c6b  and changing `WaterHeaterEntityEntityDescription` to `WaterHeaterEntityDescription` and it works fine now
