### ISSUE TITLE
elif evu_event_minutes <= 30: TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#42]
2022-12-01 00:15:37.157 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 813, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
attr.update(self.extra_state_attributes or {})
File "/config/custom_components/luxtronik2/sensor.py", line 926, in extra_state_attributes
ATTR_STATUS_TEXT: self._build_status_text(),
File "/config/custom_components/luxtronik2/sensor.py", line 888, in _build_status_text
elif evu_event_minutes <= 30:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by rhammen** [comment]
solved by chinging line 885:

if self.native_value == LUX_STATUS_EVU:
to
elif self.native_value == LUX_STATUS_EVU:

**Comment by rhammen** [comment]
without this fix, all sensors do not update anymore. 
Could this be why others experience issue #41 ?

**Comment by BenPru** [comment]
> @BenPru Now that you get more users, I think you will have to start looking into adding unit tests to your code base...

Yes, this is a good idea. I will try it.
Until this I mark newer releases as prerelease, so has everbody the choise between newest and stable code.

**Comment by BenPru** [comment]
I hope the current release [2022.12.01](https://github.com/BenPru/luxtronik/releases/tag/2022.12.01) should fix this.
Sorry for the trouble.
