### ISSUE TITLE
Error while reading datetime value 

### ISSUE THREAD

**Issue by ElBart00** [BenPru/luxtronik#53]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:690
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 06:38:25 (2 occurrences)
Last logged: 06:38:25

Error adding entities for domain sensor with platform luxtronik2
Error while setting up luxtronik2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 690, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.luxtronik2_id_web_error_time0 provides state '2022-12-13 23:24:04', which is missing timezone information

**Comment by BenPru** [comment]
Please try the current pre-release [2012.12.16a](https://github.com/BenPru/luxtronik/releases/tag/2012.12.16a)

**Comment by ElBart00** [comment]
Sorry, I'm still getting these errors in the log with version 2012.12.17

**Comment by BenPru** [comment]
@ElBart00 Unusual. I could reproduce the error with timestamps. I extend my code with a check and add for timezone information for timestamp. After that it worked for me.
Please provide me your yaml configuration, the value from the heatpump (Web interface or luxtronik lookup script)  and the current error message. Thank you.

**Comment by BenPru** [comment]
Perhaps you get a null value from your heatpump. I have change the function to handle null values. You can try the last pre-release [2022.12.18](https://github.com/BenPru/luxtronik/releases/tag/2022.12.18)
