### ISSUE TITLE
Unable to prepare setup for platform luxtronik2.update: Platform not found 

### ISSUE THREAD

**Issue by rhammen** [BenPru/luxtronik#70]
Running Pre-release 2023-01-15 or 2023-01-15a

Logger: homeassistant.setup
Source: setup.py:338
First occurred: 00:12:19 (1 occurrences)
Last logged: 00:12:19

Unable to prepare setup for platform luxtronik2.update: Platform not found (No module named 'custom_components.luxtronik2.update').

**Comment by BenPru** [comment]
2023-01-15 or 2023-01-15a have no changes between 2023-01-07 in the update sensor.
Which is the last version without this message in your case?
Can you provide the raw message from the log file?

**Comment by rhammen** [comment]
I previously used a version from end of November or early December.  If needed I can try to downgrade to pinpoint which version first caused it. 
The error message:

2023-01-16 00:17:50.402 ERROR (MainThread) [homeassistant.helpers.entity] Update for number.luxtronik2_domestic_water_thermal_desinfection_target fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik2/number.py", line 397, in update
    if domesticWaterCurrent >= float(self.native_value) and (self._last_thermal_desinfection is None or self._last_thermal_desinfection < datetime.now().date):
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'builtin_function_or_method'
2023-01-16 00:18:20.423 ERROR (MainThread) [homeassistant.helpers.entity] Update for number.luxtronik2_domestic_water_thermal_desinfection_target fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik2/number.py", line 397, in update
    if domesticWaterCurrent >= float(self.native_value) and (self._last_thermal_desinfection is None or self._last_thermal_desinfection < datetime.now().date):

**Comment by rhammen** [comment]
Ok, this one appears to be caused by myself...
While manually installing the pre-release version using the zip-file, there was a folder permission error.
I solved this so the existing files could be overwritten, but the new update.py file did not get installed and thus was missing....
I will close the issue.
