### ISSUE TITLE
Not compatible with Home Assistant 2022.5.x

### ISSUE THREAD

**Issue by scaronni** [BenPru/luxtronik#8]
Integration does not start anymore after the update:

```
Unable to prepare setup for platform luxtronik2.sensor: Platform not found (cannot import name 'ENTITY_CATEGORIES' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform luxtronik2.binary_sensor: Platform not found (cannot import name 'ENTITY_CATEGORIES' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform luxtronik2.climate: Platform not found (cannot import name 'ENTITY_CATEGORIES' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform luxtronik2.number: Platform not found (cannot import name 'ENTITY_CATEGORIES' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform luxtronik2.switch: Platform not found (cannot import name 'ENTITY_CATEGORIES' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
```

And:

```
Unexpected error importing luxtronik2/logbook.py
Unexpected error importing luxtronik2/system_health.py
Unexpected error importing luxtronik2/group.py
Unexpected error importing luxtronik2/media_source.py
Unexpected error importing luxtronik2/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.luxtronik.recorder'
```

**Comment by BenPru** [comment]
Please try the current release.
I have only changed my local code for 2022.05 - now I have synced it.

**Comment by pluskal** [comment]
Nice, thanks @BenPru the new version is working fine on 2022.05.3. Thanks!

**Comment by scaronni** [comment]
Super, thank you.
